import { RecomendLogo } from "@/lib/icons/RecomendLogo";
import { RecomendIcon } from "@/lib/icons/RecomendIcon";
import { AlertCircleIcon, ArchiveIcon, ArchiveRestoreIcon, ArrowDownNarrowWideIcon, ArrowUpNarrowWideIcon, BellIcon, BookmarkIcon, CheckIcon, ChevronDownIcon, ChevronLeftIcon, ChevronRightIcon, ChevronUpIcon, ClapperboardIcon, CompassIcon, CreditCardIcon, EditIcon, EllipsisIcon, EllipsisVerticalIcon, EyeIcon, EyeOffIcon, FilterIcon, HeartIcon, HomeIcon, ImageIcon, InfoIcon, LayoutGridIcon, LibraryIcon, LinkIcon, ListIcon, ListOrderedIcon, ListPlusIcon, ListVideoIcon, Loader2Icon, LockIcon, LogOutIcon, LucideProps, MailIcon, MapPinIcon, MenuIcon, PlusIcon, RectangleEllipsisIcon, RectangleHorizontalIcon, RectangleVerticalIcon, SearchIcon, Send, SendIcon, Settings2Icon, SettingsIcon, ShieldIcon, StarIcon, StoreIcon, TextIcon, TrashIcon, UserIcon, UserPlusIcon, UsersIcon, WallpaperIcon, XIcon, ZapIcon } from "lucide-react-native";
import { Premium } from "@/lib/icons/Premium";
import { ActivityIndicator } from "react-native";
import { Apple, Facebook, Github, Google, Instagram, Messenger, WhatsApp, X } from "@/lib/icons";

export const Icons = {
	app: {
		logo: RecomendLogo,
		icon: RecomendIcon,
	},
	brands: {
		google: Google,
		apple: Apple,
		github: Github,
		facebook: Facebook,
		instagram: Instagram,
		whatsapp: WhatsApp,
		messenger: Messenger,
		x: X,
	},
	spinner: Loader2Icon,
	Loader: ActivityIndicator,
	Archive: ArchiveIcon,
	Unarchive: ArchiveRestoreIcon,
	premium: Premium,
	home: HomeIcon,
	Text: TextIcon,
	Bell: BellIcon,
	Shield: ShieldIcon,
	CreditCard: CreditCardIcon,
	Search: SearchIcon,
	Explore: CompassIcon,
	Feed: ZapIcon,
	shop: StoreIcon,
	library: LibraryIcon,
	User: UserIcon,
	Users: UsersIcon,
	UserPlus: UserPlusIcon,
	logout: LogOutIcon,
	settings: SettingsIcon,
	info: InfoIcon,
	link: LinkIcon,
	ArrowUpNarrowWide: ArrowUpNarrowWideIcon,
	ArrowDownNarrowWide: ArrowDownNarrowWideIcon,
	ChevronUp: ChevronUpIcon,
	ChevronDown: ChevronDownIcon,
	ChevronLeft: ChevronLeftIcon,
	ChevronRight: ChevronRightIcon,
	EllipsisHorizontal: EllipsisIcon,
	EllipsisVertical: EllipsisVerticalIcon,
	Eye: EyeIcon,
	EyeOff: EyeOffIcon,
	like: HeartIcon,
	AlertCircle: AlertCircleIcon,
	Reco: SendIcon,
	Watchlist: BookmarkIcon,
	Likes: HeartIcon,
	Movie: ClapperboardIcon,
	AddPlaylist: ListPlusIcon,
	Delete: TrashIcon,
	Filters: Settings2Icon,
	Cancel: XIcon,
	Comment: TextIcon,
	Check: CheckIcon,
	Add: PlusIcon,
	Playlist: ListVideoIcon,
	Edit: EditIcon,
	Star: StarIcon,
	Mail: MailIcon,
	Password: LockIcon,
	Lock: LockIcon,
	OTP: RectangleEllipsisIcon,
	Menu: MenuIcon,
	ListOrdered: ListOrderedIcon,
	X: XIcon,
	Share: LinkIcon,
	Grid: LayoutGridIcon,
	List: ListIcon,
	RectangleHorizontal: RectangleHorizontalIcon,
	RectangleVertical: RectangleVerticalIcon,
	Wallpaper: WallpaperIcon,
	Image: ImageIcon,
	MapPin: MapPinIcon,
};